In [22]:
import numpy as np



In [23]:
A = np.array([[2, 12, 16], [2, 14, 12], [8, 2, 6], [6, 2, 16], [4, 14, 2], [8, 4, 2]])
print(A)
b = np.array([5, 8, 9])
print(b)

AN = A-b

print(AN)

[[ 2 12 16]
 [ 2 14 12]
 [ 8  2  6]
 [ 6  2 16]
 [ 4 14  2]
 [ 8  4  2]]
[5 8 9]
[[-3  4  7]
 [-3  6  3]
 [ 3 -6 -3]
 [ 1 -6  7]
 [-1  6 -7]
 [ 3 -4 -7]]


In [41]:
U, S, VT = np.linalg.svd(np.dot(np.transpose(AN), AN))

print("U:\n", U)
print("Singular values:\n", S)
print("V^T:\n", VT)

# The last row of V^T gives the normal vector of the hyperplane
normal_vector = VT[-1, :]  # Last row

print("Hyperplane coefficients (normal vector):", normal_vector)

U:
 [[-0.35805744  0.19611614  0.91287093]
 [ 0.50128041 -0.78446454  0.36514837]
 [ 0.78772636  0.58834841  0.18257419]]
Singular values:
 [2.40000000e+02 1.88000000e+02 3.18395058e-15]
V^T:
 [[-0.35805744  0.50128041  0.78772636]
 [ 0.19611614 -0.78446454  0.58834841]
 [-0.91287093 -0.36514837 -0.18257419]]
Hyperplane coefficients (normal vector): [-0.91287093 -0.36514837 -0.18257419]


In [45]:
print(normal_vector[2])
normal_vector_final = normal_vector / normal_vector[2]
print(normal_vector_final)


-0.1825741858350553
[5. 2. 1.]


In [ ]:
import numpy as np
A = np.array([[2, 8], [4, 2]])
print(A)
b = np.array([4, 5])
print(b)

AN = A-b

print(AN)

[[ 5 11]
 [11  5]]
[8 8]
[[-3  3]
 [ 3 -3]]


In [7]:
U, S, VT = np.linalg.svd(np.dot(np.transpose(AN), AN))

print("U:\n", U)
print("Singular values:\n", S)
print("V^T:\n", VT)

# The last row of V^T gives the normal vector of the hyperplane
normal_vector = VT[-1, :]  # Last row

print("Hyperplane coefficients (normal vector):", normal_vector)

U:
 [[-0.70710678  0.70710678]
 [ 0.70710678  0.70710678]]
Singular values:
 [3.60000000e+01 1.49951883e-15]
V^T:
 [[-0.70710678  0.70710678]
 [-0.70710678 -0.70710678]]
Hyperplane coefficients (normal vector): [-0.70710678 -0.70710678]


In [9]:
print(normal_vector[1])
normal_vector_final = normal_vector / normal_vector[1]
print(normal_vector_final)

-0.7071067811865475
[1. 1.]


In [ ]:
from pyomo.environ import *



In [ ]:
model - ConcreteMode()

model.x= RangeSet(1, 4)